
COMB(KC_VOLU,	KC_VOLU, KC_Y, KC_U)
COMB(KC_VOLD, 	KC_VOLD, KC_H, HM_J)
COMB(KC_MUTE, 	KC_MUTE, KC_N, M_TH)
COMB(KC_BSPC, 	KC_BSPC, KC_O, KC_P)

SUBS(vi_quit,	":q!", KC_Q, KC_W)
SUBS(vi_save,	":wq!", KC_Z, KC_X)
