// Copyright @filterpaper
// SPDX-License-Identifier: GPL-2.0+

#pragma once

// Configuration settings
#define RGB_MATRIX_TIMEOUT 180000
#define RGB_DISABLE_WHEN_USB_SUSPENDED
#define RGB_MATRIX_KEYPRESSES
#if defined (CONVERT_TO_KB2040) && defined (SPLIT_KEYBOARD)
#   define RGBW
#   define WS2812_DI_PIN 17U
#   define WS2812_PIO_USE_PIO1
#   define RGB_MATRIX_LED_COUNT 2
#   define RGB_MATRIX_LED_PROCESS_LIMIT 2
#   define RGB_MATRIX_SPLIT {1, 1}
#   define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED WS2812_DI_PIN
#endif

// Custom effects
#ifdef RGB_MATRIX_CUSTOM_USER
#   define ENABLE_RGB_MATRIX_CANDY_TAP
#   define ENABLE_RGB_MATRIX_CANDY_RAIN
#   define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CUSTOM_CANDY_TAP
#   define DEF_MODE RGB_MATRIX_DEFAULT_MODE
#   define CMK_MODE RGB_MATRIX_CUSTOM_CANDY_RAIN
#else
#   define RGB_MATRIX_SOLID_REACTIVE_GRADIENT_MODE
#   define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#   define ENABLE_RGB_MATRIX_PIXEL_RAIN
#   define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#   define DEF_MODE RGB_MATRIX_DEFAULT_MODE
#   define CMK_MODE RGB_MATRIX_PIXEL_RAIN
#endif

// Indicator flags
#ifdef KEYBOARD_crkbd_rev1
#   define CAP_FLAG LED_FLAG_UNDERGLOW
#   define MOD_FLAG LED_FLAG_UNDERGLOW
#else
#   define CAP_FLAG LED_FLAG_ALL
#   define MOD_FLAG LED_FLAG_MODIFIER
#endif

// Dimmer RGB
#define RGB_BSTEEL  55, 80, 115
#define RGB_DPURPLE 60, 0, 115
#define RGB_DPINK   115, 20, 45
#define RGB_DTEAL   5, 35, 35
#define RGB_FLUOR   75, 122, 22
#define RGB_LAYER   RGB_BSTEEL
#define RGB_MODS    RGB_GREEN
#define HSV_CAPS    HSV_PINK
#define HSV_SWAP    HSV_TEAL